apps/cart/urls.py
from django.urls import path

from apps.cart.views import *

app_name = 'cart'
urlpatterns = [
    path('', CartInfoView.as_view(), name='cart'),
    path('add/', CartAddView.as_view(), name='add'),  # 购物车记录添加
    path('update/', CartUpdateView.as_view(), name='update'),  # 购物车记录更新
    path('delete/', CartDeleteView.as_view(), name='delete'),  # 删除购物车记录

]

apps/goods/urls.py
from django.urls import path

from apps.goods.views import *

app_name = 'goods'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('goods/<goods_id>', DetailView.as_view(), name='detail'),
    path('list/<type_id>/<page>', ListView.as_view(), name='list'),
]

apps/orders/urls.py
from django.urls import path

from apps.orders.views import *

app_name = 'order'
urlpatterns = [
    path('place/', OrderPlaceView.as_view(), name='place'),
    path('commit/', OrderCommitView.as_view(), name='commit'),
]

apps/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from apps.users.views import *

app_name = 'user'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('active/<token>/', ActiveView.as_view(), name='active'),  # 用户激活
    path('', UserInfoView.as_view(), name='user'),
    path('order/<page>/', UserOrderView.as_view(), name='order'),
    path('address/', AddressView.as_view(), name='address'),
]

'''
以下为在不使用统一封装的mixin时，路由的方式
# path('', login_required(UserInfoView.as_view()), name='user'),
# path('order/', login_required(UserOrderView.as_view()), name='order'),
# path('address/', login_required(AddressView.as_view()), name='address'),
'''

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    path('search/', include('haystack.urls')),  # 全文检索框架
    path('user/', include('apps.users.urls', namespace='user')),  # 用户模块
    path('cart/', include('apps.cart.urls', namespace='cart')),  # 购物车模块
    path('order/', include('apps.orders.urls', namespace='order')),  # 订单模块
    path('', include('apps.goods.urls', namespace='goods')),  # 商品模块
]

db/apps/cart/urls.py
from django.urls import path

from apps.cart.views import *

app_name = 'cart'
urlpatterns = [
    path('', CartView.as_view(), name='cart'),
]

db/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    path('user/', include('apps.users.urls', namespace='user')),  # 用户模块
    path('cart/', include('apps.cart.urls', namespace='cart')),  # 购物车模块
    path('order/', include('apps.orders.urls', namespace='order')),  # 订单模块
    path('', include('apps.goods.urls', namespace='goods')),  # 商品模块
]

apps/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from django_redis import get_redis_connection

from apps.goods.models import GoodsSKU
from utils.mixin import LoginRequiresMixin

# 添加商品到购物车：
# 1.请求方式，采用ajax  post
# 如果设计到数据的修改（新增，更新，删除），采用post
# 如果只设计到数据 的获取，采用get
# 2.传递参数：商品id(sku_id)  商品数量(count)


class CartAddView(View):
    '''购物车记录添加'''
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先尝试获取sku_id的值
        # 如果sku_id在hash中不存在，hget返回none
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # 累加购物车中商品的数目
            count += int(cart_count)

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 设置hash中sku_id对应的值
        # hset -> 如果sku_id已经存在，更新数据，如果sku_id不存在，添加数据
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车商品的条目数
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '添加成功'})


class CartInfoView(LoginRequiresMixin, View):
    def get(self, request):
        # 获取登录的用户
        user = request.user

        # 获取用户购物车中商品的信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 商品id：商品数量
        cart_dict = conn.hgetall(cart_key)

        skus = []
        # 保护用户购物车中商品的总数目和总价格
        total_count = 0
        total_price = 0
        # 遍历获取商品的信息
        for sku_id, count in cart_dict.items():
            # 根据商品id获取商品信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price*int(count)
            # 动态给sku增加一个属性amount，保存商品的小计
            sku.amount = amount
            # 动态给sku增加一个属性count，保存购物车中对应商品的数量
            sku.count = count
            # 添加
            skus.append(sku)

            # 累加计算商品的总数目和总价格
            total_count += int(count)
            total_price += amount

        # 组织上下文
        context = {'total_count': total_count,
                   'total_price': total_price,
                   'skus': skus}

        return render(request, 'cart.html', context)


# 更新购物车记录
# 采用ajax  post请求
# 前端需要传递的参数：商品id（sku_id） 更新的商品数量（count）
class CartUpdateView(View):
    '''购物车记录更新'''
    def post(self, request):
        # 接收数据
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
            # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 校验商品库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '更新成功'})


# 删除购物车记录
# 采用ajax  post请求
# 前端需要传递的参数：商品的id（sku_id）
# cart/delete/
class CartDeleteView(View):
    '''删除购物车记录'''
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        # 接收数据
        sku_id = request.POST.get('sku_id')

        # 数据校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理：删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 删除
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 3, 'total_count': total_count, 'message': '删除成功'})

db/apps/cart/views.py
from django.shortcuts import render
from django.views import View

from utils.mixin import LoginRequiresMixin


class CartView(LoginRequiresMixin, View):
    def get(self, request):
        return render(request, 'cart.html')

templates/base.html
{#register、login、index、#}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {#网页标题内容块#}
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {#网页顶部引用文件块#}
    {% block topfiles %}{% endblock %}
</head>
<body>
{#网页顶部欢迎信息块#}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">

                {% if user.is_authenticated %}
                <div class="login_info fl">
                    欢迎您：<a href="{% url 'user:user' %}"><em>{{ user.username }}</em></a>
                </div>
                <div class="login_btn fl">
                <span>|</span>
                    <a href="{% url 'user:logout' %}">退出</a>
                </div>
                {% else %}
                <div class="login_btn fl">
                    <a href="{% url 'user:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:cart' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' 1 %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{#网页顶部搜索框块#}
{% block search_bar %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search" method="get">
			    <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock %}

{% block body %}{% endblock %}



    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
            <p>CopyRight © 2018 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
            <p>电话：010-****888     <span>|</span>     京ICP备*******8号</p>
    </div>
    {#网页底部html元素块#}
    {% block bottom %}{% endblock %}

    {#网页底部引入文件块#}
    {% block bottomfiles %}{% endblock %}
</body>
</html>

templates/base_detail_list.html
{#detail、list#}
{% extends 'base.html' %}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
                        <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {% block main_content %}{% endblock %}
{% endblock %}

templates/base_user_center.html
{#user_center_info、order、site#}
{% extends 'base_search_less.html' %}
{% block title %}天天生鲜-用户中心{% endblock %}
{% block page_title %}用户中心{% endblock %}

{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {#用户中心右侧内容块#}
		{% block right_menu %}{% endblock %}
	</div>
{% endblock %}

templates/detail.html
{% extends 'base_detail_list.html' %}
{% load static %}
{% block title %}天天生鲜-商品详情{% endblock %}

{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ sku.type.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>




                <div class="num_name fl" style="margin-left: 50px;margin-right: 10px">
                    {% for sku in same_spu_skus %}
                    {% if not sku  %}
                    {% else %}
                        <p style="width: 100px;">其他规格：</p>
                    {% endif %}
                {% endfor %}
                </div>
				<div >
                    <ul>
                    {% for sku in same_spu_skus %}
                            <button style="background-color: #ffffff;height: 52px;border-width:1px; border-style:solid">
                                <li><a style="align-content: center" href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></li>
                            </button>
                    {% endfor %}
                    </ul>
                </div>
            </div>
			<div class="total">总价：<em>16.80元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" sku_id='{{ sku.id }}' class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.price }}</div>
					    </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail|safe }}</dd>
				</dl>
			</div>

            <div class="tab_content">
				<dl>
                    {% for order in sku_order %}
                        <dt>评论时间:{{ order.update_time }}&nbsp;&nbsp;用户名:{{ order.order.user.username }}</dt>
					    <dd>评论内容:{{ order.comment }}</dd>
                    {% endfor %}
				</dl>
			</div>

		</div>
	</div>
{% endblock %}

{#网页底部html元素块#}
    {% block bottom %}
        <div class="add_jump"></div>
    {% endblock %}

{#网页底部引入文件块#}
{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
        update_goods_amount();
        {#计算商品的总价#}
        function update_goods_amount() {
            {#获取商品的单价和数量#}
            price = $('.show_pirze').children('em').text();
            count = $('.num_show').val();
            price = parseFloat(price);
            count = parseInt(count);
            {#计算商品的总价#}
            amount = price*count;
            {#设置商品的总价#}
            $('.total').children('em').text(amount.toFixed(2)+'元')
        }

        {#增加商品数量#}
        $('.add').click(function () {
            {#获取商品原有数目#}
            count = $('.num_show').val();
            {#+1#}
            count = parseInt(count)+1;
            {#重新设置商品的数目#}
            $('.num_show').val(count);
            {#更新商品的总价#}
            update_goods_amount()
        });

        {#减少商品数量#}
        $('.minus').click(function () {
            {#获取商品原有数目#}
            count = $('.num_show').val();
            {#+1#}
            count = parseInt(count)-1;
            if(count<=0){
                count = 1
            }
            {#重新设置商品的数目#}
            $('.num_show').val(count);
            {#更新商品的总价#}
            update_goods_amount()
        });

        {#手动输入商品的数量#}
        $('.num_show').blur(function () {
            {#获取用户输入的数目#}
            count = $(this).val();
            if (isNaN(count) || count.trim().length == 0 || parseInt(count) <= 0){
                count = 1
            }
            {#重新设置商品的数目#}
            $(this).val(parseInt(count));
            {#更新商品的总价#}
            update_goods_amount()
        });

        {#获取add_cart  div元素左上角的坐标 #}
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		{#获取show_count  div元素左上角的坐标#}
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;


		$('#add_cart').click(function(){
		    {#获取商品id和数量#}
            sku_id = $(this).attr('sku_id');
            count = $('.num_show').val();
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            {#组织参数#}
            params = {'sku_id': sku_id, 'count': count, 'csrfmiddlewaretoken': csrf};
            {#发起ajax  post请求    访问/cart/add，传递参数：sku_id  count#}
            $.post('/cart/add/', params, function (data) {
                if (data.res == 5){
                    {#添加成功#}
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'});
                    $(".add_jump").stop().animate({
				        'left': $to_y+7,
				        'top': $to_x+7},
                        "fast", function() {
					        $(".add_jump").fadeOut('fast',function(){
					            {#重新设置用户购物车中商品的条目数#}
						    $('#show_count').html(data.total_count);
					        });

			            });
                }
                else{
                    {#添加失败#}
                    alert(data.errmsg)
                }
            });
		})
	</script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-首页{% endblock %}

{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock %}

{% block body %}
    <div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
                <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for goods_banner in goods_banners %}
                    <li><a href="{% url 'goods:detail' goods_banner.sku.id %}"><img src="{{ goods_banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for promotion_banner in promotion_banners %}
                <a href="{{ promotion_banner.url }}"><img src="{{ promotion_banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
        <div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
                    <a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
				{% for banner in type.image_banners %}
				    <li>
                        <h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
                        <a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
                        <div class="prize">¥ {{ banner.sku.price }}</div>
				    </li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% load static %}
{% block title %}天天生鲜-商品列表{% endblock %}

{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.price }}</div>
					    </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page.object_list %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unite }}g</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
				    </li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
                    <a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">< 上一页</a>
                {% endif %}

                {% for pindex in pages %}
                    {% if pindex == skus_page.number %}
                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}

                {% endfor %}
                {% if skus_page.has_next %}
                    <a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页 ></a>
                {% endif %}

			</div>
		</div>
	</div>
{% endblock %}